on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Add your build commands here

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          # Add your test commands here

  uat:
    name: 'UAT'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: UAT Test
        run: |
          # Add your UAT test commands here

  deploy:
    name: 'Deploy'
    needs: uat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Deploy'
          change-request: |
            {
              "attributes": {
                "requested_by": {"name": "DevOps System"},
                "cmdb_ci": {"name": "*CAROL-IBM"},
                "business_service": {"name": "3Com DMI Agent Service"},
                "start_date": "2024-09-29 22:30:32",
                "end_date": "2024-09-29 22:39:32",
                "assignment_group": {"name": "Change Management"},
                "assigned_to": {"name": "Change Manager"},
                "priority": "2",
                "comments": "This is a sample pipeline script to be added in your change step",
                "work_notes": "Update this to work_notes"
                
              }
            }
